### ISSUE TITLE
Can not open / close drawer with swipe gesture

### ISSUE THREAD

**Issue by muraterd** [react-navigation/drawer#105]
I can open drawer with _**this.props.navigation.openDrawer()**_ but can not open or close with swipe gesture. What am i doing wrong here?

App.js
```
import React from 'react';
import {Button} from 'react-native';

import {createDrawerNavigator} from 'react-navigation-drawer';
import {createAppContainer} from 'react-navigation';

class MyHomeScreen extends React.Component {
  render() {
    return (
      <>
        <Button
          onPress={() => this.props.navigation.navigate('Notifications')}
          title="Go to notifications"
        />

        <Button
          onPress={() => this.props.navigation.openDrawer()}
          title="Drawer"
        />
      </>
    );
  }
}

class MyNotificationsScreen extends React.Component {
  render() {
    return (
      <Button
        onPress={() => this.props.navigation.goBack()}
        title="Go back home"
      />
    );
  }
}

const MyDrawerNavigator = createDrawerNavigator(
  {
    Home: {
      screen: MyHomeScreen,
    },
    Notifications: {
      screen: MyNotificationsScreen,
    },
  },
  {
    drawerLockMode: 'unlocked',
  },
);

export default createAppContainer(MyDrawerNavigator);

```

dependencies
```
"dependencies": {
    "react": "16.8.1",
    "react-native": "0.61.0-rc.3",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-reanimated": "^1.2.0",
    "react-native-screens": "^2.0.0-alpha.3",
    "react-navigation": "^4.0.5",
    "react-navigation-drawer": "^2.2.1",
    "react-navigation-stack": "^1.7.3"
  },
```

And i did the MainActivity setup
```
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
...
...
...
@Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegate(this, getMainComponentName()) {
      @Override
      protected ReactRootView createRootView() {
      return new RNGestureHandlerEnabledRootView(MainActivity.this);
      }
    };
  }
```

**Comment by satya164** [comment]
Can you downgrade to React Navigation 0.60 and try? I think there's some issue with 0.61 and gesture handler.

**Comment by MBach** [comment]
@satya164 : same with `react-Native: 0.60.5`

**Comment by cayasso** [comment]
Same issue here, cant close drawer in Android! I am on 0.61

**Comment by satya164** [comment]
It's fixed in https://github.com/facebook/react-native/commit/9f0dede1c913612e1241432f4cbccdc74d23a1e4 and will be released in a patch release of react-native 0.61

**Comment by netgfx** [comment]
still seeing the issue with react-native 0.61.1 and react-navigation 4.0.10

**Comment by devashishsethia** [comment]
Same issue here.  
"react-navigation": "^4.0.10",
"react-native-gesture-handler": "^1.4.1",
"react-native": "0.61.2",

**Comment by davidcort** [comment]
Why this is closed? This error still seeing in "react-native": "0.61.2" and "react-native-gesture-handler": "^1.4.1".

Please, help us  :(

**Comment by devashishsethia** [comment]
@davidcort I resolved the issue by following this : https://github.com/react-navigation/drawer/issues/105#issuecomment-534937151
You need to make changes to your MainActivity.java listed in the documentation for set up for RN version < 0.60. This has worked for me. Also, please test on a real device.

**Comment by davidcort** [comment]
@devashishsethia  that patch exists in react-native 0.61.2. But the swipe on the drawer not works. :(

**Comment by davidcort** [comment]
I resolved !!! 

in the index.js of your project:

`import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import { gestureHandlerRootHOC } from 'react-native-gesture-handler'

AppRegistry.registerComponent(appName, () => gestureHandlerRootHOC(App));`

Works in debug, not testing in release mode.

**Comment by davidcort** [comment]
Confirm. In realease mode, works like a charm. 👍

**Comment by sjonchhe** [comment]
Problem still exists on 0.61.2..

**Comment by sunilkumarrudragada** [comment]
facing same problem, any solution?

**Comment by Zeeshan666** [comment]
Problem still exists .."react-native": "0.61.4"

**Comment by du-hernandez** [comment]
I had the same problem and solved it by importing **react-native-gesture-handler** in the root of the project:

`import 'react-native-gesture-handler';`

**Comment by zubairsudofy** [comment]
In Android, you can fix it by updating the MainActivity.java file.
```
package com.example;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "Example";
    }
     @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegate(this, getMainComponentName()) {
     @Override
      protected ReactRootView createRootView() {
      return new RNGestureHandlerEnabledRootView(MainActivity.this);
     }
   };
 }
}
```

**Comment by nildes** [comment]
> In Android, you can fix it by updating the MainActivity.java file.
> 
> ```
> package com.example;
> 
> import com.facebook.react.ReactActivity;
> import com.facebook.react.ReactActivityDelegate;
> import com.facebook.react.ReactRootView;
> import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;
> 
> public class MainActivity extends ReactActivity {
> 
>     /**
>      * Returns the name of the main component registered from JavaScript.
>      * This is used to schedule rendering of the component.
>      */
>     @Override
>     protected String getMainComponentName() {
>         return "Example";
>     }
>      @Override
>   protected ReactActivityDelegate createReactActivityDelegate() {
>     return new ReactActivityDelegate(this, getMainComponentName()) {
>      @Override
>       protected ReactRootView createRootView() {
>       return new RNGestureHandlerEnabledRootView(MainActivity.this);
>      }
>    };
>  }
> }
> ```

This solve the problem on android, but sometimes it is also necessary to do react-native link to make it work!

**Comment by zenandre** [comment]
@davidcort  TKS .. :)

**Comment by phanvankhai98** [comment]
> I resolved !!!
> 
> in the index.js of your project:
> 
> ```
> import {AppRegistry} from 'react-native';
> import App from './App';
> import {name as appName} from './app.json';
> import { gestureHandlerRootHOC } from 'react-native-gesture-handler'
> 
> AppRegistry.registerComponent(appName, () => gestureHandlerRootHOC(App));
> ```
> 
> Works in debug, not testing in release mode.

Thanks

**Comment by zeeshanaligold** [comment]
> import {AppRegistry} from 'react-native';
> import App from './App';
> import {name as appName} from './app.json';
> import { gestureHandlerRootHOC } from 'react-native-gesture-handler'
> 
> AppRegistry.registerComponent(appName, () => gestureHandlerRootHOC(App));

Thank you

**Comment by waqaramjad** [comment]
> I resolved !!!
> 
> in the index.js of your project:
> 
> ```
> import {AppRegistry} from 'react-native';
> import App from './App';
> import {name as appName} from './app.json';
> import { gestureHandlerRootHOC } from 'react-native-gesture-handler'
> 
> AppRegistry.registerComponent(appName, () => gestureHandlerRootHOC(App));
> ```
> 
> Works in debug, not testing in release mode.

my application after applying that , when i touch any thing app crash

**Comment by davidcort** [comment]
> > I resolved !!!
> > in the index.js of your project:
> > ```
> > import {AppRegistry} from 'react-native';
> > import App from './App';
> > import {name as appName} from './app.json';
> > import { gestureHandlerRootHOC } from 'react-native-gesture-handler'
> > 
> > AppRegistry.registerComponent(appName, () => gestureHandlerRootHOC(App));
> > ```
> > 
> > 
> > Works in debug, not testing in release mode.
> 
> my application after applying that , when i touch any thing app crash

What version of RN and React Navigation are you using?

**Comment by shubhamkakkar** [comment]
> > > I resolved !!!
> > > in the index.js of your project:
> > > ```
> > > import {AppRegistry} from 'react-native';
> > > import App from './App';
> > > import {name as appName} from './app.json';
> > > import { gestureHandlerRootHOC } from 'react-native-gesture-handler'
> > > 
> > > AppRegistry.registerComponent(appName, () => gestureHandlerRootHOC(App));
> > > ```
> > > 
> > > 
> > > Works in debug, not testing in release mode.
> > 
> > 
> > my application after applying that , when i touch any thing app crash
> 
> What version of RN and React Navigation are you using?
`
"react-native": "0.61.5",
 "react-native-gesture-handler": "^1.5.2",
"react-navigation": "^4.0.10",
"react-navigation-drawer": "^2.3.3",
`

**Comment by davidcort** [comment]
> > > > I resolved !!!
> > > > in the index.js of your project:
> > > > ```
> > > > import {AppRegistry} from 'react-native';
> > > > import App from './App';
> > > > import {name as appName} from './app.json';
> > > > import { gestureHandlerRootHOC } from 'react-native-gesture-handler'
> > > > 
> > > > AppRegistry.registerComponent(appName, () => gestureHandlerRootHOC(App));
> > > > ```
> > > > 
> > > > 
> > > > Works in debug, not testing in release mode.
> > > 
> > > 
> > > my application after applying that , when i touch any thing app crash
> > 
> > 
> > What version of RN and React Navigation are you using?
> > `"react-native": "0.61.5",  "react-native-gesture-handler": "^1.5.2", "react-navigation": "^4.0.10", "react-navigation-drawer": "^2.3.3",`

Is very extrange, in Android works very well for me, in iOS you should change the next:
import { gestureHandlerRootHOC } from 'react-native-gesture-handler' in the first line in the index.js file.

**Comment by s3f4** [comment]
> > I resolved !!!
> > in the index.js of your project:
> > ```
> > import {AppRegistry} from 'react-native';
> > import App from './App';
> > import {name as appName} from './app.json';
> > import { gestureHandlerRootHOC } from 'react-native-gesture-handler'
> > 
> > AppRegistry.registerComponent(appName, () => gestureHandlerRootHOC(App));
> > ```
> > 
> > 
> > Works in debug, not testing in release mode.
> 
> my application after applying that , when i touch any thing app crash

same.
